### ISSUE TITLE
ClientFactory.Initialize,  how to check if connection is established ?

### ISSUE THREAD

**Issue by dawidn47** [qJake/HADotNet#14]
Hi, how to check if connection with Home Assistance is established correcly? Im asking because after checking with `ClientFactory.IsInitialized` I see true even if I set wrong ip adress of my Home Assistance. 

Another question, Can I use `ClientFactory.Initialize` with local adress ?

e. g  `ClientFactory.Initialize("https://homeassistant.local:8123/", "abcd....`

**Comment by qJake** [comment]
The `IsInitialized` property only checks if you called `Initialize` and provided some valid entries (meaning, a valid URL and not `null` or something like that), it does not reach out to HA to check connectivity.

You can check connectivity by using the `RootApiClient` or the `DiscoveryClient`.
