### ISSUE TITLE
Issue with the Await and <EntityClient>

### ISSUE THREAD

**Issue by loransAlabood** [qJake/HADotNet#2]
Hi there, 
Thanks alot for the library, this is just what I needed for my project. I fairly new to  APIs and I am trying to build an app that retrieves data from HassIO API. I have all the HassIO setup ready and I tried to retrieve data from the API using Python and it worked. However, I need to write my app using C#. I have installed your library and I tried to copy your code into an empty console program but I am getting these 2 errors that I didn't understand. 

using System;
using HADotNet;
using HADotNet.Core;

namespace HASIO_API
{

    class MainClass
    {
        public static void Main(string[] args)
        {
            string toekn = "xxxxxxxx";
            string url = "http://hassio.local:8123";

            ClientFactory.Initialize(url, toekn);

            var entityClient = ClientFactory.GetClient<EntityClient>(); 
**First Error The type or namespace name 'EntityClient' could not be found (are you missing a using directive or an assembly reference?)**

            var filteredEntityList = await entityClient.GetEntities("sun.sun");

**second error The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'**

            Console.WriteLine(filteredEntityList);

        }

    }
}

Thanks alot

**Comment by rmarkle** [comment]
This isn't an issue with this library but i'll help you out.

1.  import the Clients namespace at the top of your class `using HADotNet.Core.Clients;`
2.  There's a couple ways you can handle this.  I'd suggest you look at the following microsoft documention:  https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

**Comment by loransAlabood** [comment]
Hi Mark,

I am very sorry about that. I spent the last night trying to figure it out and I realized that the there isn’t an issue with the library. I will delete that issue. I my programming skills are basic and limited to frontend development. This is the first time I work with APIs backend development. I am using your library for my PhD thesis. One small suggestion, you might want to have more documentation. Also it would be very good if you could add a couple of examples.

Best regards,
Lorans

**Comment by qJake** [comment]
@rmarkle Thank you for helping out. For some reason I am not receiving notifications about issues in this repo, so I missed this! Strange. 🤔

@loransAlabood I think that's a great idea, I will make a note to add additional documentation and a possible example project for newcomers such as yourself. Thanks!
