### ISSUE TITLE
Deserializing array in attributes does not work

### ISSUE THREAD

**Issue by Devqon** [qJake/HADotNet#21]
## Describe the Problem

When calling the `GetAttributeValue` on a `StateObject`, it does not work in the case of (string) arrays.

## Code Sample

Simple unittest example

```csharp
[Test]
public async Task DeserializeArrayShouldWork()
{
    var statesClient = ClientFactory.GetClient<StatesClient>();
    var thermostat = await statesClient.GetState("climate.my_climate");

    // This throws an exception because it is actually a `JArray`
    var hvacModes = thermostat.GetAttributeValue<string[]>("hvac_modes");

    // This works
    var hvacModesJArray = thermostat.GetAttributeValue<JArray>("hvac_modes").Select(mode => (string) mode).ToArray();
}
```

## Possible solutions:

- Accept this and first cast to a `JArray`
       Feels hacky to me, because I have to know about Json in my host project.
- Add a custom deserializer for the `Attributes`
- Add a custom method something like `public T GetAttributeArray<T>(string name) => ((JArray) Attributes[name]).Select(v => (T) v).ToArray();`

**Comment by qJake** [comment]
@Devqon This has been fixed and will be released with v1.6.1 or higher (not published as of today).

I can confirm that this unit test now passes:

```csharp
[Test]
public async Task ShouldRetrieveStateAttributeValue()
{
    var client = ClientFactory.GetClient<StatesClient>();

    var state = await client.GetState("climate.thermostat");

    Assert.IsNotNull(state);
    Assert.AreEqual("heat_cool", state.GetAttributeValue<string[]>("hvac_modes")[0]);
}
```
