### ISSUE TITLE
Unexpected response code 0 from Home Assistant API endpoint /api/states.

### ISSUE THREAD

**Issue by markhotchkiss** [qJake/HADotNet#23]
When accessing the GetStates the following error messages is thrown.

Unexpected response code 0 from Home Assistant API endpoint /api/states.

Any pointers would be greatly appreciated.  This has only started happening recently.  The version of HA that I am using is 2021.2.1

Thanks!

**Comment by qJake** [comment]
The latest version of this library [now throws a special HTTP exception for this](https://github.com/qJake/HADotNet/blob/cad2b5a6e42d4f95aafd7fe8e9c14ca7c58d6bff/HADotNet.Core/BaseClient.cs#L59), and the [`NetworkDescription`](https://github.com/qJake/HADotNet/blob/cad2b5a6e42d4f95aafd7fe8e9c14ca7c58d6bff/HADotNet.Core/Domain/HttpResponseException.cs#L18) property will contain the network-related error (Timeout, DNS issue, etc.) that occurred.

Can you try again with the new version and let me know what the `NetworkDescription` property is set to on the `HttpResponseException` that is thrown?

**Comment by markhotchkiss** [comment]
Hi, thanks for the help!

I thought I was on the latest version, but appears not.  Upgraded and the error was actually a 401 Unauthorized.  Got a new Token and pointed my url to a https instead of http and all working again.

Thanks for the help!
