### ISSUE TITLE
project test

### ISSUE THREAD

**Issue by runtimevic** [qJake/HADotNet#3]
Hello,
in order to test the test project, 
you need to have installed in visual studio 2017, asp.net core??
Thanks you, Víctor.

**Comment by qJake** [comment]
Yes, this is a code library for use in other C# applications using Visual Studio.

If you want to open this project and view or edit the source code, you will need Visual Studio 2019. VS2017 might work, but I have not tested it. Since it's free, why not update to 2019?

**Comment by runtimevic** [comment]
Hello, 
you won't have any demo projects to see how it works.
 Thanks a lot, Víctor.

**Comment by qJake** [comment]
Yes, that's correct. Issue #6 is being tracked, we will be adding code samples for how to use this library soon. For now, you can refer to the readme file on the repo's homepage for some lightweight samples.

**Comment by glendower** [comment]
I'm have a problem getting it to work
this is what I have, i'm using vb.net on VS2019

Imports HADotNet.Core
Imports HADotNet.Core.Clients

Public Class Form1

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles Me.Load
        ClientFactory.Initialize("https://192.168.2.3:8123/", "qVXkpEkaQovdC9JT4LI_yqgfOlQU")
        SurroundingSub()

    End Sub

    Private Async Sub SurroundingSub()

        Dim configClient = ClientFactory.GetClient(Of ConfigClient)()
        Dim config = Await configClient.GetConfiguration()
        ' config.LocationName: "Home"
        ' config.Version: 0.96.1
    End Sub

End Class

I get an error 'System.NullReferenceException: 'Object reference not set to an instance of an object.'

What have I done wrong?
