### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by SamKr** [qJake/HADotNet#9]
Hey Jake, not really an issue but you're a hard man to reach - not even an e-mail address on your site ;) 

This project saved me a lot of time and is really great & fun to use, so I'd love to do a one-time donation. However, the github sponsoring system is monthly-based. Maybe add a donation button on the readme page? There are a bunch of services that provide such a service. 

Regardless; thanks for all your hard work and making it opensource!

**Comment by qJake** [comment]
Ah, thank you! Yes, my [larger project here](https://github.com/qJake/HADotNet.CommandCenter) has another donation link using Buy Me a Coffee, you can find my page here:

https://www.buymeacoffee.com/qJake

I will get this button added to this project as well, I didn't realize people were looking for it. 🙂

Thanks!
